LIBRARY_VERSION = "1.0.0"

def item(approach, presentations, skills, techniques, contraindications,
         evidence_level, sources):
    return {
        "approach": approach,
        "presentations": presentations,
        "skills": skills,
        "techniques": techniques,
        "contraindications": contraindications,
        "evidence_level": evidence_level,
        "sources": sources,
        "version": LIBRARY_VERSION,
        "approved": True,
    }

LIBRARY = [
    item("Person-Centred Therapy",
         ["grief", "relationship conflict", "low self-esteem", "adjustment"],
         ["attending", "active listening", "reflection of feelings", "validation", "silence/pacing", "goal clarification"],
         ["grief exploration", "emotional expression", "meaning-making", "support-system exploration"],
         ["Do not use supportive exploration as a substitute for urgent risk management."],
         "Established counselling approach",
         ["Rogers, C. R. (1957). The necessary and sufficient conditions of therapeutic personality change. Journal of Consulting Psychology."]),

    item("Cognitive Behavioural Therapy (CBT)",
         ["anxiety/worry", "low self-esteem", "procrastination", "low motivation", "anger"],
         ["reflection", "focusing", "open-ended questioning", "Socratic questioning", "summarisation", "strength identification"],
         ["identifying automatic thoughts", "cognitive restructuring", "evidence examination", "thought records", "behavioural activation", "graded exposure", "behavioural planning"],
         ["Exposure or intensive cognitive work requires professional assessment, pacing and suitability review."],
         "Strong evidence base across multiple common presentations",
         ["Beck, J. S. (2020). Cognitive Behavior Therapy: Basics and Beyond (3rd ed.). Guilford Press."]),

    item("Rational Emotive Behaviour Therapy (REBT)",
         ["low self-esteem", "anger", "anxiety/worry", "procrastination"],
         ["reflection", "clarification", "appropriate challenge", "confrontation/challenge"],
         ["ABC analysis", "disputing irrational beliefs", "rational coping statements"],
         ["Avoid premature disputation when rapport, safety or readiness is insufficient."],
         "Established cognitive-behavioural approach",
         ["Ellis, A. & Dryden, W. The Practice of Rational Emotive Behavior Therapy. Springer."]),

    item("Solution-Focused Brief Therapy",
         ["career uncertainty", "low motivation", "relationship conflict", "adjustment"],
         ["open-ended questioning", "focusing", "goal clarification", "strength identification"],
         ["scaling questions", "exception finding", "preferred-future questions", "small-step goal setting"],
         ["Do not bypass significant safety concerns or complex assessment needs."],
         "Established brief counselling approach",
         ["de Shazer, S. et al. (2007). More Than Miracles. Haworth."]),

    item("Motivational Interviewing",
         ["substance-use concern", "low motivation", "behaviour change"],
         ["reflective listening", "empathy", "open questions", "affirmations", "summarisation"],
         ["OARS", "change-talk elicitation", "importance/confidence scaling", "developing discrepancy"],
         ["Avoid coercive persuasion and confrontational argumentation."],
         "Strong evidence base for behaviour-change contexts",
         ["Miller, W. R. & Rollnick, S. (2013). Motivational Interviewing (3rd ed.). Guilford Press."]),

    item("Behavioural Approaches",
         ["low motivation", "procrastination", "anger", "anxiety/worry"],
         ["focusing", "goal setting", "monitoring", "summarisation"],
         ["behavioural activation", "behavioural planning", "trigger monitoring", "graded practice"],
         ["Interventions should be individualized and reviewed for safety and feasibility."],
         "Established behavioural framework",
         ["Martell, C. R., Dimidjian, S., & Herman-Dunn, R. (2010). Behavioral Activation for Depression. Guilford Press."]),

    item("Psychodynamic Approaches",
         ["relationship conflict", "recurring interpersonal patterns", "adjustment"],
         ["active listening", "reflection", "immediacy", "interpretation where appropriate"],
         ["pattern exploration", "relationship-history exploration", "meaning exploration"],
         ["Interpretation requires appropriate training, alliance and careful pacing."],
         "Established therapeutic tradition",
         ["Gabbard, G. O. (2017). Long-Term Psychodynamic Psychotherapy (3rd ed.). American Psychiatric Association Publishing."]),

    item("Gestalt Approaches",
         ["relationship conflict", "low self-esteem", "adjustment"],
         ["awareness", "focusing", "immediacy", "reflection"],
         ["here-and-now exploration", "experiential dialogue", "awareness exercises"],
         ["Experiential techniques require appropriate training and careful monitoring."],
         "Established experiential approach",
         ["Perls, F., Hefferline, R., & Goodman, P. (1951). Gestalt Therapy."]),

    item("Existential Therapy",
         ["grief", "career uncertainty", "meaning concerns", "adjustment"],
         ["empathy", "deep listening", "meaning exploration", "clarification"],
         ["meaning-making", "values exploration", "choice/responsibility exploration"],
         ["Do not substitute philosophical exploration for required risk or medical assessment."],
         "Established humanistic-existential tradition",
         ["Yalom, I. D. (1980). Existential Psychotherapy. Basic Books."]),

    item("Narrative Therapy",
         ["low self-esteem", "relationship conflict", "grief", "identity concerns"],
         ["curiosity", "questioning", "externalising language", "strength identification"],
         ["externalising conversations", "unique-outcome exploration", "re-authoring"],
         ["Maintain cultural humility and avoid imposing an alternative identity narrative."],
         "Established counselling approach",
         ["White, M. & Epston, D. (1990). Narrative Means to Therapeutic Ends. Norton."]),

    item("Family Systems Approaches",
         ["relationship conflict", "family conflict"],
         ["circular questioning", "clarification", "focusing", "immediacy"],
         ["relationship mapping", "interaction-pattern exploration", "communication work"],
         ["Consider safety, coercion, confidentiality and appropriateness before conjoint work."],
         "Established systemic framework",
         ["Nichols, M. P. (2020). Family Therapy: Concepts and Methods (12th ed.). Pearson."]),

    item("Trauma-Informed Approaches",
         ["trauma-related concerns"],
         ["safety", "grounding", "choice", "validation", "pacing"],
         ["stabilisation", "grounding", "resource building", "safety planning"],
         ["Do not force trauma disclosure or processing; urgent safety needs take priority."],
         "Trauma-informed framework",
         ["SAMHSA (2014). Concept of Trauma and Guidance for a Trauma-Informed Approach."]),

    item("Mindfulness-Based Approaches",
         ["anxiety/worry", "stress", "low mood"],
         ["present-moment focusing", "non-judgmental listening", "pacing"],
         ["mindful breathing", "grounding", "attention exercises"],
         ["Adapt exercises for individual suitability; stop if distress increases."],
         "Established adjunctive approach",
         ["Kabat-Zinn, J. (1990). Full Catastrophe Living. Delacorte."]),

    item("Strengths-Based Counselling",
         ["low self-esteem", "career uncertainty", "adjustment", "low motivation"],
         ["strength identification", "validation", "goal clarification", "encouragement"],
         ["strength mapping", "resource identification", "goal setting"],
         ["Do not use strengths language to minimize suffering or risk."],
         "Established counselling orientation",
         ["Saleebey, D. (2013). The Strengths Perspective in Social Work Practice. Pearson."]),

    item("Integrative / Eclectic Counselling",
         ["complex or mixed presentation"],
         ["active listening", "reflection", "empathy", "focusing", "summarisation"],
         ["sequenced interventions selected from reviewed approaches"],
         ["Requires explicit rationale, competence and professional oversight when combining approaches."],
         "Integrative framework",
         ["Norcross, J. C. & Goldfried, M. R. (2005). Handbook of Psychotherapy Integration. Oxford University Press."]),
]
